# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-16 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp', models.CharField(max_length=10)),
                ('ww', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PLAN_STATUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptp', models.CharField(max_length=10)),
                ('pbom', models.CharField(max_length=7)),
                ('ppilots', models.BooleanField(default=False)),
                ('pyield', models.BooleanField(default=False)),
                ('pbs', models.BooleanField(default=False)),
                ('ptherm', models.BooleanField(default=False)),
                ('pb2b', models.BooleanField(default=False)),
                ('pqa', models.BooleanField(default=False)),
                ('pinitwtl', models.BooleanField(default=False)),
                ('pfinwtl', models.BooleanField(default=False)),
                ('pfwp', models.BooleanField(default=False)),
                ('pfuse', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TEST_TIME_MODULE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=3)),
                ('bom', models.CharField(max_length=7)),
                ('location', models.CharField(max_length=6)),
                ('tp', models.CharField(max_length=20)),
                ('team', models.CharField(max_length=20)),
                ('module', models.CharField(max_length=20)),
                ('instance_and_tt', django_mysql.models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='TEST_TIME_TP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=3)),
                ('bom', models.CharField(max_length=7)),
                ('location', models.CharField(max_length=6)),
                ('tp', models.CharField(max_length=20)),
                ('phi', models.IntegerField(default=0)),
                ('module_and_tt', django_mysql.models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='VPO_DESC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tp', models.CharField(max_length=10)),
                ('bom', models.CharField(max_length=7)),
                ('ww', models.CharField(default='', max_length=10)),
                ('vpo', models.CharField(default='', max_length=13)),
                ('site', models.CharField(max_length=6)),
                ('units', models.IntegerField()),
                ('device', models.CharField(max_length=20)),
                ('source_lot', models.CharField(max_length=100)),
                ('locations', models.CharField(max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='VPO_LOC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpo', models.CharField(default='', max_length=13)),
                ('location', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('bin_desc', models.CharField(default='', max_length=300)),
                ('yield_val', models.CharField(default='', max_length=20)),
                ('vpo_program', models.TextField(default='')),
                ('vpo_part', models.TextField(default='')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vpo_loc',
            unique_together=set([('vpo', 'location')]),
        ),
    ]
