# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-12 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_status',
            name='pbom',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='test_time_module',
            name='bom',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='test_time_tp',
            name='bom',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vpo_desc',
            name='bom',
            field=models.CharField(max_length=15),
        ),
    ]
