# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-12 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0002_auto_20181212_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpo_desc',
            name='locations',
            field=models.CharField(max_length=40),
        ),
    ]
