# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-06 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0003_auto_20181212_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpo_desc',
            name='tp',
            field=models.CharField(max_length=20),
        ),
    ]
