# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-15 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0004_auto_20190306_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='tp',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vpo_desc',
            name='tp',
            field=models.CharField(max_length=30),
        ),
    ]
