# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-03-15 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0005_auto_20190315_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_status',
            name='ptp',
            field=models.CharField(max_length=30),
        ),
    ]
