# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-16 21:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bin2Bin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(default='empty', max_length=20)),
                ('old_tp_bom', models.CharField(default='empty', max_length=40)),
                ('new_bin', models.CharField(default='empty', max_length=10)),
                ('old_bin', models.CharField(default='empty', max_length=10)),
                ('explanation', models.TextField()),
                ('vmin', models.TextField()),
                ('tester_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TP',
            fields=[
                ('tp_bom', models.CharField(default='empty', max_length=40, primary_key=True, serialize=False)),
                ('vpos', models.TextField()),
                ('mainTP', models.CharField(max_length=30)),
                ('Bom', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='bin2bin',
            name='tp_name',
            field=models.ForeignKey(db_column='tp_bom', on_delete=django.db.models.deletion.CASCADE, related_name='bin2bin', to='tpi_tools.TP'),
        ),
    ]
