# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-12-12 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpi_tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tp',
            name='Bom',
            field=models.CharField(max_length=10),
        ),
    ]
