# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-09 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpi_tools', '0002_auto_20181212_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin2bin',
            name='new_bin',
            field=models.CharField(default='empty', max_length=21),
        ),
        migrations.AlterField(
            model_name='bin2bin',
            name='old_bin',
            field=models.CharField(default='empty', max_length=21),
        ),
    ]
