# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-15 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpi_tools', '0003_auto_20190109_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tp',
            name='tp_bom',
            field=models.CharField(default='empty', max_length=50, primary_key=True, serialize=False),
        ),
    ]
