# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-01-16 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpi_tools', '0004_auto_20190115_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tp',
            name='tp_bom',
            field=models.CharField(default='empty', max_length=70, primary_key=True, serialize=False),
        ),
    ]
