# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-05-08 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tpi_tools', '0005_auto_20190115_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin2bin',
            name='new_bin',
            field=models.CharField(default='empty', max_length=30),
        ),
        migrations.AlterField(
            model_name='bin2bin',
            name='old_bin',
            field=models.CharField(default='empty', max_length=30),
        ),
    ]
