    <collection type=material>
    <group>
    J736118CR SITE=SVC
    </group>
    </collection>
    <analysis app=cb >
    TOOL=SCPREFETCH
    /HASCLASS=T
    /SEPARATEBY=NONE
    CLASSDISPLAY=RAW
    DISPLAYAS=TABLE
    SORTDISPLAY=RAW
    /COMBINEPARTFLOW
    /FORMAT=CSV
    /OUTPUT='I:\CMT_ENG\skx\tpi\user\rshibano\web\The-Cool-VPO-Tool\checker\static\checker\temp_files\outputR.csv'
    /ASMERLIN
    </analysis>
